menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Large Language Models [zerocoder.ru]', url: 'https://zerocoder.ru/prompt-engineer-with-ai-course'}
- {name: 'Deep Learning [netology.ru]', url: 'https://netology.ru/programs/prodatascience'}

social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/mr-ivan-rodin'}
- {icon: 'telegram', link: 'https://t.me/aimazing_materials'}
- {icon: 'github', link: 'https://github.com/RodinIvan'}

contacts:
- {name: 'Ivan Rodin', title: 'Postdoctoral Researcher', department: 'Computer Science', institution: 'University of Catania', institution_address: 'Catania, Italy', email: 'ivan.rodin@unict.it', image: 'assets/img/me_official_sq.jpg'}
